#!/bin/env python3

## =========================================================================
## Copyright (C) 2022 Pavol Federl (pfederl@ucalgary.ca)
## All Rights Reserved. Do not distribute this file.
## =========================================================================
## DO NOT EDIT THIS FILE. DO NOT SUBMIT THIS FILE FOR GRADING.
##
## you can use this script to generate random input
## the script takes a single command line argument - number of requests

import random, sys
from random import randrange as rr

tagRange = (1,99)
reqSize = (1,10000)
freeProb = 0.3

if __name__ == "__main__":
    n = 100
    if len(sys.argv) != 2:
        print(f"generating {n} lines", file=sys.stderr)
    else:
        n = int(sys.argv[1])

    reqs = []
    nfree = int(freeProb * n)
    for i in range(n - nfree):
        reqs.append(f"{rr(*tagRange)} {rr(*reqSize)}")
    for i in range(nfree):
        reqs.append(f"-{rr(*tagRange)}")

    random.shuffle(reqs)

    print("\n".join(reqs))
            
    
