/// =========================================================================
/// Copyright (C) 2022 Pavol Federl (pfederl@ucalgary.ca)
/// All Rights Reserved. Do not distribute this file.
/// =========================================================================
/// DO NOT EDIT THIS FILE. DO NOT SUBMIT THIS FILE FOR GRADING.

#include "common.h"
#include <cctype>
#include <chrono>
#include <iostream>

using VS = std::vector<std::string>;

// split string p_line into vector of strings (words)
// the delimiters are 1 or more whitespaces
VS split(const std::string & p_line)
{
    auto line = p_line + " ";
    VS res;
    bool in_str = false;
    std::string curr_word = "";
    for (auto c : line) {
        if (isspace(c)) {
            if (in_str)
                res.push_back(curr_word);
            in_str = false;
            curr_word = "";
        } else {
            curr_word.push_back(c);
            in_str = true;
        }
    }
    return res;
}

int Word2Int::get(const std::string & w)
{
    auto f = myset.find(w);
    if (f == myset.end()) {
        myset[w] = counter;
        counter++;
        return counter - 1;
    }
    return f->second;
}
