/// =========================================================================
/// Copyright (C) 2022 Pavol Federl (pfederl@ucalgary.ca)
/// All Rights Reserved. Do not distribute this file.
/// =========================================================================
/// DO NOT EDIT THIS FILE. DO NOT SUBMIT THIS FILE FOR GRADING.

#pragma once
#include <string>
#include <vector>

struct Result {
    int index;
    std::vector<std::string> procs;
};

Result find_deadlock(const std::vector<std::string> & edges);
