#!/bin/env python3

# =========================================================================
# Copyright (C) 2022 Pavol Federl (pfederl@ucalgary.ca)
# All Rights Reserved. Do not distribute this file.
# =========================================================================
# DO NOT EDIT THIS FILE. DO NOT SUBMIT THIS FILE FOR GRADING.
#
# Random FAT generator
import random, textwrap, sys


def main(argv):
    assert len(argv) in range(1, 4)
    n = 10
    if len(argv) >= 2:
        n = int(argv[1])
    if len(argv) == 3:
        random.seed(argv[2])
    fat = []
    while len(fat) < n:
        fat.append(random.randint(0, n - 1))
    for b in random.sample(range(n), random.choice(range(n // 10 + 2))):
        fat[b] = -1
    para = " ".join([str(n) for n in fat])
    tw = textwrap.TextWrapper()
    print(tw.fill(para))


if __name__ == "__main__":
    main(sys.argv)
